# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-26 05:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coque',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(max_length=255, null=True)),
                ('prix', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(max_length=255, null=True)),
                ('prix', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('coque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carGeneration.Coque')),
                ('module1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='option1', to='carGeneration.Module')),
                ('module2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='option2', to='carGeneration.Module')),
                ('module3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='option3', to='carGeneration.Module')),
                ('module4', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='option4', to='carGeneration.Module')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('duration', models.IntegerField()),
                ('prix', models.FloatField()),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carGeneration.Profil')),
            ],
        ),
        migrations.CreateModel(
            name='Siege',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(max_length=255, null=True)),
                ('prix', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pseudo', models.CharField(max_length=25, unique=True)),
                ('mail', models.EmailField(max_length=50, unique=True)),
                ('mdp', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='reservation',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carGeneration.Utilisateur'),
        ),
        migrations.AddField(
            model_name='profil',
            name='siege1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='siege1', to='carGeneration.Siege'),
        ),
        migrations.AddField(
            model_name='profil',
            name='siege2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='siege2', to='carGeneration.Siege'),
        ),
        migrations.AddField(
            model_name='profil',
            name='siege3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='siege3', to='carGeneration.Siege'),
        ),
        migrations.AddField(
            model_name='profil',
            name='siege4',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='siege4', to='carGeneration.Siege'),
        ),
        migrations.AddField(
            model_name='profil',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carGeneration.Utilisateur'),
        ),
    ]
