# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-26 01:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carGeneration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='mail',
            field=models.EmailField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='mdp',
            field=models.CharField(max_length=50),
        ),
    ]
